version: '3.9'
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: exam
      POSTGRES_PASSWORD: exam
      POSTGRES_DB: exam
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  app:
    build: .
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: http://localhost:3000
      DATABASE_URL: postgresql://exam:exam@db:5432/exam
      SHADOW_DATABASE_URL: postgresql://exam:exam@db:5432/exam_shadow
      REDIS_RATE_LIMIT: "true"
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
volumes:
  pgdata:
